/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package vocal.ist;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int andforge=0x7f020000;
        public static final int fahrplan=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int image=0x7f020003;
        public static final int image2=0x7f020004;
        public static final int mic1=0x7f020005;
        public static final int mic2=0x7f020006;
        public static final int play=0x7f020007;
        public static final int play1=0x7f020008;
        public static final int play2=0x7f020009;
        public static final int play2foc=0x7f02000a;
        public static final int rec=0x7f02000b;
        public static final int rec1foc=0x7f02000c;
        public static final int rec1st=0x7f02000d;
        public static final int sound=0x7f02000e;
        public static final int stop1=0x7f02000f;
        public static final int stop2=0x7f020010;
    }
    public static final class id {
        public static final int play=0x7f05000a;
        public static final int rec=0x7f050009;
        public static final int sound=0x7f050008;
        public static final int speak=0x7f050001;
        public static final int speak_label=0x7f050004;
        public static final int text=0x7f050007;
        public static final int vokabelList=0x7f050002;
        public static final int werbung=0x7f050003;
        public static final int werbung2=0x7f050005;
        public static final int widget28=0x7f050006;
        public static final int widget41=0x7f050000;
    }
    public static final class layout {
        public static final int dolmetscher=0x7f030000;
        public static final int list_row=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
